matches:
- trigger: ':date:'
  replace: '{{mytime}}'
- trigger: ':now:'
  replace: '{{mytime}}'
- trigger: ':dates:'
  replace: '{{mytime}}'
- trigger: ':shell:'
  replace: '{{output}}'
- trigger: ':ups:'
  replace: sudo nala update && sudo nala upgrade -y
