theme = "catppuccin_mocha"

[editor]
color-modes = true
line-number = "relative"
mouse = false
# end-of-line-diagnostics = "inline-diagnostics"
bufferline = "multiple"
popup-border = "all"

[editor.statusline]
left = ["mode", "version-control"]
center = ["file-name", "file-modification-indicator"]
right = [
	"diagnostics",
	"selections",
	"position",
	"position-percentage",
	"total-line-numbers",
	"file-encoding",
	"spinner",
	"file-type",
]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.indent-guides]
render = true
character = "╎"

# [editor.inline-diagnostics]
# cursor-line = "warning"
